apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: event-manager
  name: event-manager-{{.SHARD}}
  namespace: projectsveltos
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: event-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: event-manager
    spec:
      containers:
      - args:
        - --diagnostics-address=:8443
        - --shard-key={{.SHARD}}
        - --v=5
        - --version=main
        command:
        - /manager
        image: docker.io/projectsveltos/event-manager@sha256:88819a67e9407f1b736f8d04bf4e07370525b50dd7f654ec693d4f08366b62b5
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
      serviceAccountName: event-manager
      terminationGracePeriodSeconds: 10
