apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: sc-manager
  name: sc-manager-{{.SHARD}}
  namespace: projectsveltos
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: sc-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: sc-manager
    spec:
      containers:
      - args:
        - --diagnostics-address=:8443
        - --shard-key={{.SHARD}}
        - --v=5
        command:
        - /manager
        image: docker.io/projectsveltos/sveltoscluster-manager@sha256:2862cbfe6a9259a0ca5aa5601751f9f2dae810f0e8c04ce5bfd47f863274e8e2
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
      serviceAccountName: sc-manager
      terminationGracePeriodSeconds: 10
