---
# Needs to create projectsveltos deployments
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: controller-role-extra
  namespace: projectsveltos
rules:
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - "*"